FROM python:3.9-slim-buster

WORKDIR /app

COPY generate-data.py .

RUN pip install opentelemetry-api opentelemetry-sdk opentelemetry-exporter-otlp opentelemetry-instrumentation

CMD ["python", "generate-data.py"]
