FROM python:3.9-slim-buster

WORKDIR /app

COPY generate-data.py .

RUN pip install --upgrade pip
RUN python3 -m pip install -U Flask
RUN pip install opentelemetry-instrumentation-flask opentelemetry-api opentelemetry-sdk opentelemetry-exporter-otlp opentelemetry-instrumentation opentelemetry-exporter-prometheus

CMD ["python3", "generate-data.py"]
